Repository SchwarzIT/terraform-provider-stackit, pull requests merged in 2022-11, with the labels that each got.

#44 filter for supported versions when loading version options
  stackit/internal/data-sources/postgres-flex/instance/data_source_test.go
  stackit/internal/resources/kubernetes/helpers.go
  stackit/internal/resources/kubernetes/validations.go
Labels: bug

#45 update version
  README.md
  docs/index.md
  examples/provider/provider.tf
Labels: documentation

#50 Add LogMe resource and data source
  docs/data-sources/logme_instance.md
  docs/resources/logme_instance.md
  examples/data-sources/stackit_logme_instance/data-source.tf
  examples/resources/stackit_logme_instance/resource.tf
  go.mod
  go.sum
  stackit/internal/data-sources/logme/instance/actions.go
  stackit/internal/data-sources/logme/instance/data_source.go
  stackit/internal/data-sources/logme/instance/data_source_test.go
  stackit/internal/data-sources/logme/instance/schema.go
  stackit/internal/resources/logme/instance/actions.go
  stackit/internal/resources/logme/instance/helpers.go
  stackit/internal/resources/logme/instance/resource.go
  stackit/internal/resources/logme/instance/resource_test.go
  stackit/internal/resources/logme/instance/schema.go
  stackit/provider.go
Labels: enhancement
